apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cfo6da3bf-nodejs
  janus-idp.io/tekton: cfo6da3bf-nodejs
  backstage.io/kubernetes-id: cfo6da3bf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cfo6da3bf-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
