apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cfo6da3bf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cfo6da3bf-nodejs 
  name: cfo6da3bf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cfo6da3bf-nodejs 
